# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMMpZr_64eskTHerULXXH7BFW6AY8vWO
"""

import numpy as np

"""1.

"""

a = np.arange(0,10,1)
print(a)
b = a[::-1]
print(b)

"""2.

"""

a = np.arange(9)
a33 = a.reshape(3,3)
a91 = a.reshape(9,1)
a33, a91

"""3."""

a = np.ones((10,10), dtype = int)
a[1:9,1:9] = 0
a

"""4."""

a = np.ones((5,5), dtype = int)

a[::2,::2] = 0
a[1::2,1::2] = 0
a

"""5.

"""

a = np.arange(10)
b = np.array([1,1,1,1,1,-1,-1,-1,-1,1])
result = a*b
result

"""6."""

X = np.array([[4,5],[7,10]])
Y = np.array([[2,3],[1,5]])
result = X @ Y
result

"""7."""

import matplotlib.pyplot as plt
import math

x1 = np.linspace(-10,10,100)
y1 = 1/(1+np.exp(-x))
y2 = y1 * (1-y1)

plt.plot(x,y)
plt.plot(x,y2)
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.show

